//user action types
const USER_LOADED="USER_LOADED"
const USER_LOADING="USER_LOADING"
const LOGIN_SUCCESS="LOGIN_SUCCESS"
const LOGIN_FAIL="LOGIN_FAIL"
const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
const REGISTER_SUCCESS="REGISTER_SUCCESS"
const REGISTER_FAIL="REGISTER_FAIL"
const SET_TOKEN="SET_TOKEN"
const AUTH_ERROR="AUTH_ERROR"

export {USER_LOADED,AUTH_ERROR, USER_LOADING, LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT_SUCCESS, REGISTER_SUCCESS, REGISTER_FAIL, SET_TOKEN  }

//error action types
const GET_ERRORS="GET_ERRORS"
const CLEAR_ERRORS="CLEAR_ERRORS"

export {GET_ERRORS, CLEAR_ERRORS}
